=== spixians/test/order.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="https://www.w3schools.com" 
    xmlns="https://www.w3schools.com" elementFormDefault="qualified">

    <xs:complexType name="purchase">
        <xs:sequence>
            <xs:element name="id" type="xs:string" maxOccurs="1"/>
            <xs:element name="quantity" type="xs:string" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="orderinfo">
        <xs:sequence>
            <xs:element name="oid" type="xs:string" maxOccurs="1"/>
            <xs:element name="pid" type="xs:string" maxOccurs="1"/>
            <xs:element name="purchases" type="purchase" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    

    <xs:element name="orderstore">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="order" type="orderinfo" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== spixians/test/order_store.xml
<?xml version="1.0"?>
<orderstore xmlns="https://www.w3schools.com" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="order.xsd">
  <order>
    <oid>1</oid>
    <pid>p1</pid>
    <purchases>
      <id>1</id>
      <quantity>2</quantity>
    </purchases>
    <purchases>
      <id>4</id>
      <quantity>1</quantity>
    </purchases>
    <purchases>
      <id>2</id>
      <quantity>2</quantity>
    </purchases>
  </order>

  <order>
    <oid>2</oid>
    <pid>p2</pid>
    <purchases>
      <id>3</id>
      <quantity>4</quantity>
    </purchases>
    <purchases>
      <id>2</id>
      <quantity>1</quantity>
    </purchases>
  </order>

  <order>
    <oid>3</oid>
    <pid>p2</pid>
    <purchases>
      <id>2</id>
      <quantity>1</quantity>
    </purchases>
  </order>
</orderstore>
